### ISSUE TITLE
Access to cs_detail?

### ISSUE THREAD

**Issue by waywardmonkeys** [richo/capstone-rs#7]
For something I'm working with, I'd like to be able to access `cs_detail` and get back info about registers read and written. (It might be useful to just wrap the actual `cs_detail` struct and make it easy to get access to all of the various details?)

This will require having a binding to set `cs_option` to generate detail.

**Comment by tmfink** [comment]
I'm currently working on exposing some of detail interface in my branch:
https://github.com/tmfink/capstone-rs/tree/cs-detail

I do not plan supporting `cs_reg_read` and `cs_reg_write` yet because they require instruction ids. The architecture-specific capstone includes (such as [x86.h](https://github.com/aquynh/capstone/blob/8925ff9bde4faad8fbb5ae499e38ba29159252a4/include/x86.h)) are very large. We need to automatically parse them.
